version: '3.5'
services:
  master:
    build: ./
    image: wiin/kind
    privileged: true
    cgroup_parent: master
    cap_add:
      - ALL
    command: kubeadm init --ignore-preflight-errors=ALL --config /kubeadm/kubeadm.config
    volumes:
      - kubelet-cache:/docker-state
      - ./master.cfg:/kubeadm/kubeadm.config
      - ./cni.yml:/cni/cni.yml
    networks:
      k8s:
        ipv4_address: 172.16.99.99

  node:
    image: wiin/kind
    privileged: true
    cgroup_parent: nodes
    cap_add:
      - ALL
    command: kubeadm join 172.16.99.99:6443 --token w9nw9n.w9nw9nw9nw9nw9nw --ignore-preflight-errors=ALL  --config /kubeadm/node.cfg --discovery-token-unsafe-skip-ca-verification=true
    volumes:
      - kubelet-cache:/docker-state
      - ./node.cfg:/kubeadm/node.cfg
    networks:
      - k8s

volumes:
  kubelet-cache:
    driver_opts:
      type: none
      device: $PWD/state
      o: bind

networks:
  k8s:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.99.0/24
